---
name: i18n Upgrade

on:
  push:
  pull_request:

jobs:
  i18n-upgrade:
    runs-on: ubuntu-latest
    name: Upgrade i18n

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade setuptools
          pip install Babel

      - name: Generate base.pot
        run: pybabel extract -o locale/base.pot pidroidbot_discord/

#      for each new lang
#      pybabel init -l en_US -i locale/base.pot -d locale

      - name: Upadate catalogs
        run: pybabel update -i locale/base.pot -d locale

      - name: Compile catalogs
        run: pybabel compile -d locale

      - name: Push upgrades
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: internationalization
#          FOLDER: docs/build/html

#pybabel init -l fr_FR en_US -i locale/base.pot -d locale
#pybabel update -i locale/base.pot -d locale
#pybabel compile -d locale

#          for l in locale/*/ ; do
#            echo "--- Locale : $l ---"
#            # pybabel init -l en_US -i locale/base.pot -d locale
#            pybabel update -d locale -l "$l" -i locale/base.pot -D "base"
#            pybabel compile -d locale -l "$l" -D "base"
#          done

#          for f in locale/**/LC_MESSAGES/*.po ; do
#            pybabel update -i locale/base.pot -o "$f"
#            pybabel compile -i "$f" -o "${f%.*}.mo"
#          done

#            msgmerge --update "$f" locale/base.pot
#            msgfmt -o "${f_po%.*}.mo" "${f}"

#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pygettext

#    - name: Install GNU gettext
#      run: sudo apt-get install gettext
#
#
#
#
#
#    - name: CCheck i18n format
#      run: |
#        for i in pidroidbot_discord/locale/**/*.po ; do
#          echo "checking $i..."
#          msgfmt -v -c -o /dev/null $i
#        done
#
#    - name: Check i18n coverage
#      id: i18nCoverage
#      uses: alexkiro/i18n-coverage@v1.0.0
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        translations-path: 'pidroidbot_discord/locale/**/*.po'
#
#    - name: Get the coverage
#      run: echo "The coverage was ${{ steps.i18nCoverage.outputs.coverage }}"