---
name: i18n Upgrade

on:
  push:
  pull_request:

jobs:
  i18n-upgrade:
    runs-on: ubuntu-latest

    name: Upgrade i18n
    steps:
    - uses: actions/checkout@v2

    - uses: elementary/actions/gettext-template@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        translation_branch: 'i18n'
        regenerate_po: 'true'

# pygettext -a -d base -p locale/ pidroidbot_discord/* -v
#

#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.x'
#
##    - name: Install dependencies
##      run: |
##        python -m pip install --upgrade pip
##        pip install pygettext
#
#    - name: Install GNU gettext
#      run: sudo apt-get install gettext
#
#
#
#
#
#    - name: CCheck i18n format
#      run: |
#        for i in pidroidbot_discord/locale/**/*.po ; do
#          echo "checking $i..."
#          msgfmt -v -c -o /dev/null $i
#        done
#
#    - name: Check i18n coverage
#      id: i18nCoverage
#      uses: alexkiro/i18n-coverage@v1.0.0
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        translations-path: 'pidroidbot_discord/locale/**/*.po'
#
#    - name: Get the coverage
#      run: echo "The coverage was ${{ steps.i18nCoverage.outputs.coverage }}"