---
#https://github.com/alexkiro/i18n-coverage
name: i18n Coverage

on:
  push:
    paths:
    - 'locale/**/LC_MESSAGES/*.pao'
  pull_request:
    paths:
    - 'locale/**/LC_MESSAGES/*.pao'

jobs:
  i18n-coverage:
    runs-on: ubuntu-latest
    name: Check i18n coverage
    steps:
    - uses: actions/checkout@v2

#      - name: Install GNU gettext
#        run: sudo apt-get install gettext
#
#      - name: Check i18n format
#        run: |
#          for i in locale/**/*.po ; do
#            echo "checking $i..."
#            msgfmt -v -c -o /dev/null $i
#          done

    - name: Check i18n coverage
      id: i18nCoverage
      uses: alexkiro/i18n-coverage@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        translations-path: 'locale/**/LC_MESSAGES/*.po'

#https://img.shields.io/badge/i18n Coverage-50%25-green

#    - name: Get the coverage
#      run: echo "The coverage was ${{ steps.i18nCoverage.outputs.coverage }}"

    - name: Update badge
      run: |
        badge="s#.. image:: https://img.shields.io/badge/i18n Coverage-.*$#.. image:: https://img.shields.io/badge/i18n Coverage-${{ steps.i18nCoverage.outputs.coverage }}%25-green#"
        alt="s#:alt: i18n Coverage .*$#:alt: i18n Coverage ${{ steps.i18nCoverage.outputs.coverage }}%#"
        sed -i "$badge" README.rst
        sed -i "$alt" README.rst